core/urls.py
from django.urls import path
from django.conf.urls import url, include
from .views import (
					ItemDetailView, 
					HomeView,
					OrderSummaryView,
					CheckoutView, 
					add_to_cart, 
					remove_from_cart,
					remove_single_item_from_cart,
					PaymentView,
                    AddCouponView,
                    RefundRequestView
					)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order_summary/', OrderSummaryView.as_view(), name = 'order_summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add_to_cart/<slug>/', add_to_cart, name = 'add_to_cart'),
    path('add_coupon/', AddCouponView.as_view(), name = 'add_coupon'),
    path('remove_from_cart/<slug>/', remove_from_cart, name = 'remove_from_cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name = 'remove_single_item_from_cart'),
    #Here our slug is payment_option.
    path('payment/<payment_option>/', PaymentView.as_view(), name = 'payment'),
    path('request_refund/', RefundRequestView.as_view(), name='request_refund'),
    ]

core/models.py
                                       #THIS ALL GONNA SHOW UP IN ADMIN PAGE.

                                       
from django.db.models.signals import post_save
from django.conf import settings #bcz auth is in settings.
from django.db import models
from django.shortcuts import reverse
#from django_countries.fields import CountryField



# Create your models here.

CATEGORY_CHOICES=(('S', 'Shirt'),
				  ('SW', 'Sportswear'),
				  ('OW', 'Outwear'),
				  ('MP', 'Cell Phone'),
				  ('TV', 'Television'),
				  ('EC', 'Electronics'))

LABEL_CHOICES = (('P', 'primary'),
				 ('S', 'secondary'),
				 ('D', 'danger'))

ADDRESS_CHOICES = (('B', 'Billing'),
					('S', 'Shipping'))

# WE created two things CATEGORY_CHOICES and LABEL_CHOICES inside Item section to display it on admin-page

class UserProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
	stripe_customer_id = models.CharField(max_length = 50, blank=True, null=True)
	one_click_purchasing = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username



class Item(models.Model):  # This is displayed at list of items.
	title = models.CharField(max_length=100)
	price = models.FloatField()
	discount_price = models.FloatField(blank=True, null=True)
	category = models.CharField(choices = CATEGORY_CHOICES, max_length=2)
	label = models.CharField(choices = LABEL_CHOICES, max_length=1)
	description = models.TextField()
	slug = models.SlugField()
	image = models.ImageField()


	def __str__(self):
		return self.title
    
    #  These are REVERSE function!

	def get_absolute_url(self):
		return reverse("core:product", kwargs={'slug':self.slug})
			
	def get_add_to_cart_url(self):
		return reverse("core:add_to_cart", kwargs={'slug':self.slug})

	def get_remove_from_cart_url(self):
		return reverse("core:remove_from_cart", kwargs={'slug':self.slug})




class OrderItem(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	ordered = models.BooleanField(default = False)
	item = models.ForeignKey(Item, on_delete=models.CASCADE) #Linking item with Item
	quantity = models.IntegerField(default=1) #when we call add_to_cart function then for adding item we need quantity field.

	def __str__(self):
		return f"{self.quantity} of {self.item.title}"

	def get_total_item_price(self):
		return self.quantity * self.item.price

	def get_total_discount_item_price(self):
		return self.quantity * self.item.discount_price

	def get_amount_saved(self):
		return self.get_total_item_price() - self.get_total_discount_item_price()

	def get_final_price(self):
		if self.item.discount_price:
			return self.get_total_discount_item_price()
		return self.get_total_item_price()



class Order(models.Model):  # You can basically view this as Cart.
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) #Just taking user
	ref_code = models.CharField(max_length=20, blank=True, null = True) #reference code for tracking order.
	items = models.ManyToManyField(OrderItem)  #Adding OderItems into Order.
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField()
	ordered = models.BooleanField(default = False)
	#This Field for referencing the Payment
	payment = models.ForeignKey('Payment', on_delete = models.SET_NULL, blank=True, null = True)
	#This Field for referencing the Shipping_Address
	shipping_address = models.ForeignKey('Address', related_name= 'shipping_address', on_delete = models.SET_NULL, blank=True, null = True)
	#This Field for referencing the Billing_Address
	billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete = models.SET_NULL, blank=True, null = True) 
	#This Field for referencing the Coupn.
	coupon = models.ForeignKey('Coupon', on_delete = models.SET_NULL, blank=True, null=True)

	#These fields keep track of order
	being_delivered = models.BooleanField(default=False)
	recieved = models.BooleanField(default=False)
	refund_requested = models.BooleanField(default=False)
	refund_granted = models.BooleanField(default=False)

	'''
	1. Item Added to cart
	2. Adding a billing address
	 (failed checkout due to not having valid stripe keys.)
	3. Payment
	 (preprocessing, processing, packaging etc)
	4. Being delivered
	5. Recieved
	6. Refunds
	'''

	def __str__(self):
		return self.user.username

	def get_total(self):
		total=0
		for order_item in self.items.all(): #Looping through all the items
			total += order_item.get_final_price()
		if self.coupon:
			total -= self.coupon.amount #when we apply coupon it gonna subtract amount in coupon.
		return total

def __str__(self):
	return self.title

class Address(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) #Just taking user
	street_address = models.CharField(max_length=100)
	apartment_address = models.CharField(max_length=100)
	#country = CountryField(multiple = False)
	zip = models.CharField(max_length=100)
	address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
	default = models.BooleanField(default = False)

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name_plural = 'Addresses'


#Keeping track of Stripe payment
class Payment(models.Model):
	stripe_charge_id = models.CharField(max_length=50)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
	#on_delete.SET_NULL this is when we delete user payment don't got deleted.
	amount = models.FloatField()
	timestamp = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.user.username

class Coupon(models.Model):
	code = models.CharField(max_length=15)
	amount = models.FloatField()

	def __str__(self):
		return self.code

class Refund(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE)
	reason = models.TextField()
	accepted = models.BooleanField(default=False)
	email = models.EmailField()

	def __str__(self):
		return f"{self.pk}" #we returned like this bcz it's an id not a string.


def userprofile_reciever(sender, instance, created, *args, **kwargs):
	if created:
		userprofile = UserProfile.objects.create(user=instance)

post_save.connect(userprofile_reciever, sender = settings.AUTH_USER_MODEL)

templates/home.html
{% extends 'base.html' %}
{% load cart_template_tags %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>E-Commerce</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="" target="_blank">
        <strong class="blue-text">E-Commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          
        </ul>

        <!-- Right -->

        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a  href="{% url 'core:order_summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect"  href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect"  href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect"  href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
         
          
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
  
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in object_list %}

          <!--Grid column-->
          
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <!--<img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"-->
                  
                <img src="{{ item.image.url }}"  class="card-img-top">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if item.discount_price %}
                  {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}
                </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->
          </div>
          {% endfor %}
          <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row-->
       

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © Aakif_and_Krishna
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %} "></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

{% endblock content %}

templates/item_list.html
{% extends 'base.html' %}

{% block content %}

<h2>Here is the List of items </h2>
{% for item in items %}

{{ item }}
{% endfor %}


{% endblock content %}

templates/order_snippet.html

                                              <!--THIS IS COUPON CODE FORM-->

<div class="col-md-12 mb-4">

  <!-- Heading -->
  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
  </h4>

  <!-- Cart -->
  <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
        <small class="text-muted">{{ order_item.item.description }}</small>
      </div>
      <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
      </div>
      <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
      <span>Total (USD)</span>
      <strong>${{ order.get_total }}</strong>
    </li>
  </ul>
  <!-- Cart -->
 <!-- Promo code -->
{% if DISPLAY_COUPON_FORM %}
<form class="card p-2" action="{% url 'core:add_coupon' %}" method="POST">
  <div class="input-group">
    {% csrf_token %}
    <!--<input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">-->
    {{ couponform.code }} <!--Taking form with help of couponform and accessing code -->
    <div class="input-group-append">
      <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
    </div>
  </div>
</form>
{% endif %}
          <!-- Promo code -->

</div>

templates/order_summary.html
{% extends 'base.html' %}
{% load cart_template_tags %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>E-Commerce</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>
  
  <!--/.Carousel Wrapper-->


<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:home' %}" >
        <strong class="blue-text">E-Commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          
        </ul>

        <!-- Right -->

        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect"  href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect"  href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect"  href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
         
          
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->


<main >
  <div class ="container">
    <div class="table-responsive text-nowrap">
  <h2>Order Summary </h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Item Title</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Item Price</th>

      </tr>
    </thead>
    <tbody>
      {% for order_item in object.items.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><b>{{ order_item.item.title }}</b></td>
        <td><b>${{ order_item.item.price }}</b></td>

        <td><a href="{% url 'core:remove_single_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
          <b>{{ order_item.quantity }}</b>
          <a href="{% url 'core:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
        </td>

        <td>
          {% if order_item.item.discount_price %}
            <b>${{ order_item.get_total_discount_item_price }}</b>
            <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
          {% else %}
            ${{ order_item.get_total_item_price }}
          {% endif %}
          <a href="{% url 'core:remove_from_cart' order_item.item.slug %}">
            <i class="fas fa-trash float-right"></i>
          </a>


        </td>
      </tr>

      {% empty %}
      <tr>
        <td colspan="5"><b>Your Cart is Empty!</b></td>
      </tr>

      <tr>
        <td colspan="5">
          <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
        </td>
      </tr>

      {% endfor %}

      {% if object.coupon %}
      <tr>
        <td colspan="4"><b>Coupon Discount</b></td>
        <td><b>-${{ object.coupon.amount }}</b></td>
      </tr>
      {% endif %}


      {% if object.get_total %}
      <tr>
        <td colspan="4"><b>Order Total</b></td>
        <td><b>${{ object.get_total }}</b></td>
      </tr>

       <tr>
        <td colspan="5">
          <a class="btn btn-warning float-right ml-2" href="/checkout/" >Proceed to checkout</a>
          <a class="btn btn-primary float-right" href="/" >Continue shopping</a>
        </td>
      </tr>
      {% endif %}

    </tbody>
  </table>
</div>


  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © Aakif Jafri
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %} "></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

{% endblock content %}

